// Runtime schema mirrors the SQL migrations in drizzle/. Apply them using Wrangler.
import {sql} from 'drizzle-orm';
import {sqliteTable,text,integer,index,primaryKey,uniqueIndex} from 'drizzle-orm/sqlite-core';
export const clubs=sqliteTable('clubs',{id:text('id').primaryKey(),inviteCode:text('invite_code').notNull().unique()});
export const photoCleanup=sqliteTable('photo_cleanup',{photoKey:text('photo_key').primaryKey()});
export const users=sqliteTable('users',{id:text('id').primaryKey(),username:text('username').notNull().unique(),name:text('name').notNull(),passwordHash:text('password_hash').notNull(),salt:text('salt').notNull(),clubId:text('club_id').notNull().references(()=>clubs.id),createdAt:integer('created_at').notNull(),rankingPublic:integer('ranking_public').notNull().default(1),nudgesEnabled:integer('nudges_enabled').notNull().default(1)});
export const posts=sqliteTable('posts',{id:text('id').primaryKey(),userId:text('user_id').notNull(),name:text('name').notNull(),kind:text('kind').notNull(),minutes:integer('minutes').notNull(),note:text('note').notNull(),photoKey:text('photo_key'),createdAt:integer('created_at').notNull(),clubId:text('club_id')},t=>[index('posts_created_at').on(t.createdAt),index('posts_user_id').on(t.userId),index('posts_club_created').on(t.clubId,t.createdAt)]);
export const cheers=sqliteTable('cheers',{postId:text('post_id').notNull().references(()=>posts.id,{onDelete:'cascade'}),userId:text('user_id').notNull()},t=>[primaryKey({columns:[t.postId,t.userId]})]);
export const pokes=sqliteTable('pokes',{id:text('id').primaryKey(),senderId:text('sender_id').notNull(),recipientId:text('recipient_id').notNull(),createdAt:integer('created_at').notNull(),readAt:integer('read_at')},t=>[index('pokes_recipient_id').on(t.recipientId),index('pokes_created_at').on(t.createdAt),uniqueIndex('pokes_daily').on(t.senderId,t.recipientId,sql`CAST((${t.createdAt}+32400000)/86400000 AS INTEGER)`)]);
export const sessions=sqliteTable('sessions',{tokenHash:text('token_hash').primaryKey(),userId:text('user_id').notNull().references(()=>users.id,{onDelete:'cascade'}),expiresAt:integer('expires_at').notNull()},t=>[index('sessions_expiry').on(t.expiresAt)]);
export const authLimits=sqliteTable('auth_limits',{key:text('key').primaryKey(),attempts:integer('attempts').notNull(),expiresAt:integer('expires_at').notNull()},t=>[index('auth_limits_expiry').on(t.expiresAt)]);
export const goalChanges=sqliteTable('goal_changes',{userId:text('user_id').notNull().references(()=>users.id,{onDelete:'cascade'}),effectiveWeek:integer('effective_week').notNull(),days:integer('days').notNull()},t=>[primaryKey({columns:[t.userId,t.effectiveWeek]})]);
export const challenges=sqliteTable('challenges',{id:text('id').primaryKey(),clubId:text('club_id').notNull().references(()=>clubs.id),creatorId:text('creator_id').notNull().references(()=>users.id),title:text('title').notNull(),kind:text('kind').notNull(),targetDays:integer('target_days').notNull(),startsAt:integer('starts_at').notNull(),endsAt:integer('ends_at').notNull(),createdAt:integer('created_at').notNull()},t=>[index('challenges_club').on(t.clubId,t.startsAt)]);
export const challengeMembers=sqliteTable('challenge_members',{challengeId:text('challenge_id').notNull().references(()=>challenges.id,{onDelete:'cascade'}),userId:text('user_id').notNull().references(()=>users.id,{onDelete:'cascade'})},t=>[primaryKey({columns:[t.challengeId,t.userId]})]);
